name: Post Deploy Tasks
on:
  workflow_run:
    workflows: ["Build And Deploy"]  # must match the `name:` in your other workflow
    types:
      - completed

jobs:
  post-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Post-deploy Task
        run: echo "Running post-deployment steps in sequence..."
